### ISSUE TITLE
How to specify custom ruleset?

### ISSUE THREAD

**Issue by svivian** [chindit/actions-phpcs#3]
Is there no way to specify a different XML file for a custom ruleset? I don't have `phpcs.xml.dist` and don't want to clog up the root directory with it. I have a `ruleset.xml` in another folder.

Or what about custom cmd flags so I can add `--standard=path/to/ruleset.xml`

**Comment by chindit** [comment]
That's a good idea.

**Comment by chindit** [comment]
@svivian I've added a `cli` arguments on `master` branch.
You can try it by using `uses: chindit/actions-phpcs@master` and setting your CLI args here:
```
 with:
     cli: 'YOUR_CLI_ARGS'
```

Let me know if your have any issue.

**Comment by svivian** [comment]
Yep all seems to work, thanks!
